server:
  port: 80

filter:
  white-list: /server,/projects/list,/websockets,/users/login,/users/register,/users/loginConfig,/swagger,/v3/api-docs,/doc.html,/folder/upload,/keepFiles/,/imageFiles/,/recordFiles/,/logFiles/,/packageFiles/

spring:
  cloud:
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 314572800
      routes:
        - id: controller
          uri: lb://sonic-server-controller
          predicates:
            - Path=/api/controller/**, /api/transport/**
          filters:
            - StripPrefix=2
        - id: folder
          uri: lb://sonic-server-folder
          predicates: Path=/api/folder/**
          filters:
            - StripPrefix=2
        - id: transport
          uri: lb:ws://sonic-server-controller
          predicates:
            - Path=/websockets/**
          filters:
            - StripPrefix=1

        - id: dev-controller
          uri: lb://sonic-server-controller
          predicates:
            - Path=/server/api/controller/**, /server/api/transport/**
          filters:
            - StripPrefix=3
        - id: dev-folder
          uri: lb://sonic-server-folder
          predicates: Path=/server/api/folder/**
          filters:
            - StripPrefix=3
        - id: dev-transport
          uri: lb:ws://sonic-server-controller
          predicates:
            - Path=/server/websockets/**
          filters:
            - StripPrefix=2